export const ROUTER_PATHS = {
  HOME: "/",
  FEED: "/feed",
  ORDER_BY_ID: "/order/",
  INGREDIENTS: "/ingredients",
  INGREDIENT_BY_ID: "/ingredients/:id",
  PROFILE: "/profile",
  PROFILE_ORDERS: "/profile/orders",
  PROFILE_ORDER_BY_ID: "/profile/orders/:id",
  SIGN_IN: "/auth/login",
  SIGN_UP: "/auth/register",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESET_PASSWORD: "/auth/reset-password",
  404: "/not-found",
  403: "/forbidden",
};
