import type { Metadata } from "next";
import { JetBrains_Mono, Iceland } from "next/font/google";
import "./globals.css";
import { AppLayout } from "./_/layouts/app-layout";
import { LayoutNavbar } from "~/widgets/layout-navbar";
import { AppLoader } from "./_/loaders/app-loader";
import { loadAppLoaderData } from "./_/loaders/load-app-loader-data";

const JetBrainsMonoFont = JetBrains_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-jetbrains",
  display: "swap",
});

const IcelandFont = Iceland({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-iceland",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await loadAppLoaderData();
  return (
    <html lang="en">
      <body
        className={`${IcelandFont.variable} ${JetBrainsMonoFont.variable} antialiased`}
      >
        <AppLoader data={{ session }}>
          <AppLayout navbar={<LayoutNavbar />}>{children}</AppLayout>
        </AppLoader>
      </body>
    </html>
  );
}
