"use client";
/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Full API - Users, Sessions and Burgers
 * API for managing ingredients, orders and user authentication
 * OpenAPI spec version: 1.0.0
 */
import useSwr from "swr";
import type { Key, SWRConfiguration } from "swr";

import useSWRMutation from "swr/mutation";
import type { SWRMutationConfiguration } from "swr/mutation";

import { createInstance } from "./api-instance";
import type { ErrorType, BodyType } from "./api-instance";
/**
 * Type of the ingredient
 */
export type IngredientType =
  (typeof IngredientType)[keyof typeof IngredientType];

export const IngredientType = {
  bun: "bun",
  sauce: "sauce",
  main: "main",
} as const;

export interface IngredientObjectDto {
  _id: string;
  name: string;
  type: IngredientType;
  proteins: number;
  fat: number;
  carbohydrates: number;
  calories: number;
  price: number;
  image: string;
  image_mobile: string;
  image_large: string;
  __v: number;
  /** Optional unique identifier for frontend usage */
  uniqueId?: string;
}

export interface UserObject {
  email: string;
  name: string;
}

export interface LoginFormDataDto {
  email: string;
  password: string;
}

export type UserObjectWithPasswordDtoAllOf = {
  password: string;
};

export type UserObjectWithPasswordDto = UserObject &
  UserObjectWithPasswordDtoAllOf;

export interface PasswordWithToken {
  password: string;
  token: string;
}

export interface TokenObjectDto {
  success: boolean;
  accessToken: string;
  refreshToken: string;
}

export interface RefreshTokenRequest {
  /** Valid refresh token */
  token: string;
}

export type UserWithTokensAllOf = {
  user: UserObject;
};

export type UserWithTokens = TokenObjectDto & UserWithTokensAllOf;

export type OrderObjectOrder = {
  number: number;
};

export interface OrderObject {
  name: string;
  order: OrderObjectOrder;
}

export type DetailedOrderObjectStatus =
  (typeof DetailedOrderObjectStatus)[keyof typeof DetailedOrderObjectStatus];

export const DetailedOrderObjectStatus = {
  done: "done",
  pending: "pending",
  created: "created",
} as const;

export interface DetailedOrderObject {
  ingredients: string[];
  _id: string;
  name: string;
  status: DetailedOrderObjectStatus;
  number: number;
  createdAt: string;
  updatedAt: string;
}

/**
 * Error response
 */
export interface ApiError {
  success: boolean;
  message: string;
}

export type GetIngredients200 = {
  success: boolean;
  data: IngredientObjectDto[];
};

export type GetAuthUser200 = {
  success: boolean;
  user: UserObject;
};

export type PatchAuthUser200 = {
  success: boolean;
  user: UserObject;
};

export type PostAuthLogin200AllOf = {
  success?: boolean;
};

export type PostAuthLogin200 = UserWithTokens &
  PostAuthLogin200AllOf &
  Required<Pick<UserWithTokens & PostAuthLogin200AllOf, "success">>;

export type PostAuthRegister200AllOf = {
  success?: boolean;
};

export type PostAuthRegister200 = UserWithTokens &
  PostAuthRegister200AllOf &
  Required<Pick<UserWithTokens & PostAuthRegister200AllOf, "success">>;

export type PostAuthLogoutBody = {
  token: string;
};

export type PostAuthLogout200 = {
  success: boolean;
  message: string;
};

export type PostAuthToken200AllOf = {
  success?: boolean;
};

export type PostAuthToken200 = TokenObjectDto & PostAuthToken200AllOf;

export type PostPasswordResetBody = {
  email: string;
};

export type PostPasswordReset200 = {
  success: boolean;
  message: string;
};

export type PostPasswordResetReset200 = {
  success: boolean;
  message: string;
};

export type GetOrders200 = {
  success: boolean;
  orders: DetailedOrderObject[];
  total: number;
  totalToday: number;
};

export type PostOrdersBody = {
  ingredients: string[];
};

export type PostOrders200AllOf = {
  name?: string;
  success: boolean;
};

export type PostOrders200 = OrderObject & PostOrders200AllOf;

export type GetOrdersAll200 = {
  success: boolean;
  orders: DetailedOrderObject[];
  total: number;
  totalToday: number;
};

export type GetOrdersId200 = {
  success: boolean;
  orders: DetailedOrderObject[];
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Get list of all available ingredients
 */
export const getIngredients = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<GetIngredients200>(
    { url: `/ingredients`, method: "GET" },
    options,
  );
};

export const getGetIngredientsKey = () => [`/ingredients`] as const;

export type GetIngredientsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getIngredients>>
>;
export type GetIngredientsQueryError = ErrorType<unknown>;

/**
 * @summary Get list of all available ingredients
 */
export const useGetIngredients = <TError = ErrorType<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getIngredients>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetIngredientsKey() : null));
  const swrFn = () => getIngredients(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Get current user data
 */
export const getAuthUser = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<GetAuthUser200>(
    { url: `/auth/user`, method: "GET" },
    options,
  );
};

export const getGetAuthUserKey = () => [`/auth/user`] as const;

export type GetAuthUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthUser>>
>;
export type GetAuthUserQueryError = ErrorType<unknown>;

/**
 * @summary Get current user data
 */
export const useGetAuthUser = <TError = ErrorType<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getAuthUser>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetAuthUserKey() : null));
  const swrFn = () => getAuthUser(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Update user data
 */
export const patchAuthUser = (
  userObjectWithPasswordDto: BodyType<UserObjectWithPasswordDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<PatchAuthUser200>(
    {
      url: `/auth/user`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: userObjectWithPasswordDto,
    },
    options,
  );
};

export const getPatchAuthUserMutationFetcher = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return (
    _: Key,
    { arg }: { arg: UserObjectWithPasswordDto },
  ): Promise<PatchAuthUser200> => {
    return patchAuthUser(arg, options);
  };
};
export const getPatchAuthUserMutationKey = () => [`/auth/user`] as const;

export type PatchAuthUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchAuthUser>>
>;
export type PatchAuthUserMutationError = ErrorType<unknown>;

/**
 * @summary Update user data
 */
export const usePatchAuthUser = <TError = ErrorType<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof patchAuthUser>>,
    TError,
    Key,
    UserObjectWithPasswordDto,
    Awaited<ReturnType<typeof patchAuthUser>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPatchAuthUserMutationKey();
  const swrFn = getPatchAuthUserMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary User login
 */
export const postAuthLogin = (
  loginFormDataDto: BodyType<LoginFormDataDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<PostAuthLogin200>(
    {
      url: `/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: loginFormDataDto,
    },
    options,
  );
};

export const getPostAuthLoginMutationFetcher = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return (
    _: Key,
    { arg }: { arg: LoginFormDataDto },
  ): Promise<PostAuthLogin200> => {
    return postAuthLogin(arg, options);
  };
};
export const getPostAuthLoginMutationKey = () => [`/auth/login`] as const;

export type PostAuthLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthLogin>>
>;
export type PostAuthLoginMutationError = ErrorType<unknown>;

/**
 * @summary User login
 */
export const usePostAuthLogin = <TError = ErrorType<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postAuthLogin>>,
    TError,
    Key,
    LoginFormDataDto,
    Awaited<ReturnType<typeof postAuthLogin>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostAuthLoginMutationKey();
  const swrFn = getPostAuthLoginMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Register new user
 */
export const postAuthRegister = (
  userObjectWithPasswordDto: BodyType<UserObjectWithPasswordDto>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<PostAuthRegister200>(
    {
      url: `/auth/register`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: userObjectWithPasswordDto,
    },
    options,
  );
};

export const getPostAuthRegisterMutationFetcher = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return (
    _: Key,
    { arg }: { arg: UserObjectWithPasswordDto },
  ): Promise<PostAuthRegister200> => {
    return postAuthRegister(arg, options);
  };
};
export const getPostAuthRegisterMutationKey = () => [`/auth/register`] as const;

export type PostAuthRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRegister>>
>;
export type PostAuthRegisterMutationError = ErrorType<unknown>;

/**
 * @summary Register new user
 */
export const usePostAuthRegister = <TError = ErrorType<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postAuthRegister>>,
    TError,
    Key,
    UserObjectWithPasswordDto,
    Awaited<ReturnType<typeof postAuthRegister>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostAuthRegisterMutationKey();
  const swrFn = getPostAuthRegisterMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary User logout
 */
export const postAuthLogout = (
  postAuthLogoutBody: BodyType<PostAuthLogoutBody>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<PostAuthLogout200>(
    {
      url: `/auth/logout`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postAuthLogoutBody,
    },
    options,
  );
};

export const getPostAuthLogoutMutationFetcher = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return (
    _: Key,
    { arg }: { arg: PostAuthLogoutBody },
  ): Promise<PostAuthLogout200> => {
    return postAuthLogout(arg, options);
  };
};
export const getPostAuthLogoutMutationKey = () => [`/auth/logout`] as const;

export type PostAuthLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthLogout>>
>;
export type PostAuthLogoutMutationError = ErrorType<unknown>;

/**
 * @summary User logout
 */
export const usePostAuthLogout = <TError = ErrorType<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postAuthLogout>>,
    TError,
    Key,
    PostAuthLogoutBody,
    Awaited<ReturnType<typeof postAuthLogout>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostAuthLogoutMutationKey();
  const swrFn = getPostAuthLogoutMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * Exchange refresh token for new access token
 * @summary Refresh access token
 */
export const postAuthToken = (
  refreshTokenRequest: BodyType<RefreshTokenRequest>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<PostAuthToken200>(
    {
      url: `/auth/token`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: refreshTokenRequest,
    },
    options,
  );
};

export const getPostAuthTokenMutationFetcher = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return (
    _: Key,
    { arg }: { arg: RefreshTokenRequest },
  ): Promise<PostAuthToken200> => {
    return postAuthToken(arg, options);
  };
};
export const getPostAuthTokenMutationKey = () => [`/auth/token`] as const;

export type PostAuthTokenMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthToken>>
>;
export type PostAuthTokenMutationError = ErrorType<ApiError>;

/**
 * @summary Refresh access token
 */
export const usePostAuthToken = <TError = ErrorType<ApiError>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postAuthToken>>,
    TError,
    Key,
    RefreshTokenRequest,
    Awaited<ReturnType<typeof postAuthToken>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostAuthTokenMutationKey();
  const swrFn = getPostAuthTokenMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Request password reset
 */
export const postPasswordReset = (
  postPasswordResetBody: BodyType<PostPasswordResetBody>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<PostPasswordReset200>(
    {
      url: `/password-reset`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postPasswordResetBody,
    },
    options,
  );
};

export const getPostPasswordResetMutationFetcher = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return (
    _: Key,
    { arg }: { arg: PostPasswordResetBody },
  ): Promise<PostPasswordReset200> => {
    return postPasswordReset(arg, options);
  };
};
export const getPostPasswordResetMutationKey = () =>
  [`/password-reset`] as const;

export type PostPasswordResetMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPasswordReset>>
>;
export type PostPasswordResetMutationError = ErrorType<unknown>;

/**
 * @summary Request password reset
 */
export const usePostPasswordReset = <TError = ErrorType<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postPasswordReset>>,
    TError,
    Key,
    PostPasswordResetBody,
    Awaited<ReturnType<typeof postPasswordReset>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostPasswordResetMutationKey();
  const swrFn = getPostPasswordResetMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Reset password with token
 */
export const postPasswordResetReset = (
  passwordWithToken: BodyType<PasswordWithToken>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<PostPasswordResetReset200>(
    {
      url: `/password-reset/reset`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: passwordWithToken,
    },
    options,
  );
};

export const getPostPasswordResetResetMutationFetcher = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return (
    _: Key,
    { arg }: { arg: PasswordWithToken },
  ): Promise<PostPasswordResetReset200> => {
    return postPasswordResetReset(arg, options);
  };
};
export const getPostPasswordResetResetMutationKey = () =>
  [`/password-reset/reset`] as const;

export type PostPasswordResetResetMutationResult = NonNullable<
  Awaited<ReturnType<typeof postPasswordResetReset>>
>;
export type PostPasswordResetResetMutationError = ErrorType<unknown>;

/**
 * @summary Reset password with token
 */
export const usePostPasswordResetReset = <
  TError = ErrorType<unknown>,
>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postPasswordResetReset>>,
    TError,
    Key,
    PasswordWithToken,
    Awaited<ReturnType<typeof postPasswordResetReset>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostPasswordResetResetMutationKey();
  const swrFn = getPostPasswordResetResetMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Get user orders
 */
export const getOrders = (options?: SecondParameter<typeof createInstance>) => {
  return createInstance<GetOrders200>(
    { url: `/orders`, method: "GET" },
    options,
  );
};

export const getGetOrdersKey = () => [`/orders`] as const;

export type GetOrdersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrders>>
>;
export type GetOrdersQueryError = ErrorType<ApiError>;

/**
 * @summary Get user orders
 */
export const useGetOrders = <TError = ErrorType<ApiError>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getOrders>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetOrdersKey() : null));
  const swrFn = () => getOrders(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Create new order
 */
export const postOrders = (
  postOrdersBody: BodyType<PostOrdersBody>,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<PostOrders200>(
    {
      url: `/orders`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postOrdersBody,
    },
    options,
  );
};

export const getPostOrdersMutationFetcher = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return (_: Key, { arg }: { arg: PostOrdersBody }): Promise<PostOrders200> => {
    return postOrders(arg, options);
  };
};
export const getPostOrdersMutationKey = () => [`/orders`] as const;

export type PostOrdersMutationResult = NonNullable<
  Awaited<ReturnType<typeof postOrders>>
>;
export type PostOrdersMutationError = ErrorType<unknown>;

/**
 * @summary Create new order
 */
export const usePostOrders = <TError = ErrorType<unknown>>(options?: {
  swr?: SWRMutationConfiguration<
    Awaited<ReturnType<typeof postOrders>>,
    TError,
    Key,
    PostOrdersBody,
    Awaited<ReturnType<typeof postOrders>>
  > & { swrKey?: string };
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const swrKey = swrOptions?.swrKey ?? getPostOrdersMutationKey();
  const swrFn = getPostOrdersMutationFetcher(requestOptions);

  const query = useSWRMutation(swrKey, swrFn, swrOptions);

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Get all orders
 */
export const getOrdersAll = (
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<GetOrdersAll200>(
    { url: `/orders/all`, method: "GET" },
    options,
  );
};

export const getGetOrdersAllKey = () => [`/orders/all`] as const;

export type GetOrdersAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrdersAll>>
>;
export type GetOrdersAllQueryError = ErrorType<unknown>;

/**
 * @summary Get all orders
 */
export const useGetOrdersAll = <TError = ErrorType<unknown>>(options?: {
  swr?: SWRConfiguration<Awaited<ReturnType<typeof getOrdersAll>>, TError> & {
    swrKey?: Key;
    enabled?: boolean;
  };
  request?: SecondParameter<typeof createInstance>;
}) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetOrdersAllKey() : null));
  const swrFn = () => getOrdersAll(requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};

/**
 * @summary Get order details by ID
 */
export const getOrdersId = (
  id: string,
  options?: SecondParameter<typeof createInstance>,
) => {
  return createInstance<GetOrdersId200>(
    { url: `/orders/${id}`, method: "GET" },
    options,
  );
};

export const getGetOrdersIdKey = (id: string) => [`/orders/${id}`] as const;

export type GetOrdersIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrdersId>>
>;
export type GetOrdersIdQueryError = ErrorType<unknown>;

/**
 * @summary Get order details by ID
 */
export const useGetOrdersId = <TError = ErrorType<unknown>>(
  id: string,
  options?: {
    swr?: SWRConfiguration<Awaited<ReturnType<typeof getOrdersId>>, TError> & {
      swrKey?: Key;
      enabled?: boolean;
    };
    request?: SecondParameter<typeof createInstance>;
  },
) => {
  const { swr: swrOptions, request: requestOptions } = options ?? {};

  const isEnabled = swrOptions?.enabled !== false && !!id;
  const swrKey =
    swrOptions?.swrKey ?? (() => (isEnabled ? getGetOrdersIdKey(id) : null));
  const swrFn = () => getOrdersId(id, requestOptions);

  const query = useSwr<Awaited<ReturnType<typeof swrFn>>, TError>(
    swrKey,
    swrFn,
    swrOptions,
  );

  return {
    swrKey,
    ...query,
  };
};
